//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hortas.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HortasZonas
    {
        public int Id { get; set; }
        public int IdHorta { get; set; }
        public int IdZona { get; set; }
        public decimal Preco { get; set; }
        public bool Activo { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
    
        public virtual Hortas Hortas { get; set; }
        public virtual Zonas Zonas { get; set; }
    }
}
